### PR TITLE
Update RISC-V and AVR GCC to version 11

### PR DESCRIPTION
**Pull request by rleh**
- [x] RISC-V GCC 11.1.0
- [x] AVR-GCC 11.2.0
  - modm-io/avr-gcc#4

### CODE REVIEW

**Review by salkinium — APPROVED** [review]

**Comment by salkinium** [comment]
I'd also be grateful if you're motivated to upgrade our avr-gcc build to v11. It has low priority though, since ARM GCC 11 will probably not be released for a while.

**Comment by rleh** [comment]
Absolutely, but our avr-gcc v11 is not ready yet: modm-io/avr-gcc#4 (Maybe I'll spent some time on it next week...)

**Comment by salkinium** [comment]
Oh, you're way ahead of me ;-P

**Comment by chris-durand** [comment]
> Absolutely, but our avr-gcc v11 is not ready yet: [modm-io/avr-gcc#4](https://github.com/modm-io/avr-gcc/pull/4) (Maybe I'll spent some time on it next week...)

Let me know, when I should update the AVR C++ standard library. It will take some effort.

**Comment by rleh** [comment]
> I'd also be grateful if you're motivated to upgrade our avr-gcc build to v11.

Done.

Merge?

**Comment by salkinium** [comment]
I'm not sure, @chris-durand can we can compile libc++ v10 in modm with GCC v11 in our docker container?

**Comment by chris-durand** [comment]
> I'm not sure, @chris-durand can we can compile libc++ v10 in modm with GCC v11 in our docker container?

I'd guess so. Only the other direction should be problematic. GCC is generally backwards compatible. The only worries I would have are some bugs or regressions in the new AVR backend introduced in GCC 11.

**Comment by rleh** [comment]
Maybe we should use the version tags of the images instead of `:latest` in modm CI?

The CI run from this PR already published the new docker images: https://github.com/modm-ext/docker-modm-build/pkgs/container/modm-build-cortex-m

**Comment by chris-durand** [comment]
> The CI run from this PR already published the new docker images: https://github.com/modm-ext/docker-modm-build/pkgs/container/modm-build-cortex-m

That doesn't sound like a good idea to do a release every time someone runs a pipeline on a PR successfully. Shouldn't we only publish it after merge or after creating a tag or something similar?

**Comment by salkinium** [comment]
> Maybe we should use the version tags of the images instead of :latest in modm CI?

Yes, and it's a little more work, but we have to manually switch the compiler versions anyways for the macOS and Windows CIs with their explicit download/homebrew links, so it would be good to coordinate that controllably.

**Comment by rleh** [comment]
> Yes, and it's a little more work, but we have to manually switch the compiler versions anyways for the macOS and Windows CIs with their explicit download/homebrew links, so it would be good to coordinate that controllably.

-> modm-io/modm#803

**Comment by rleh** [comment]
Merge here?

**Review by salkinium — APPROVED** [review]
Go for merge.

**Pull request merged**
