### PR TITLE
Update Doxypress to 1.4.2

### PR DESCRIPTION
**Pull request by rleh**
I heard from @daixtrose that @agserm has release a new version of Doxypress!
Thanks for notifying!

### CODE REVIEW

**Comment by agserm** [comment]
Thanks for pinging us on this. Your change is correct and will work, but we are now hosting downloads on github as well so you can have a permanent URL and only update versions when desired. The URL for this release is:

https://github.com/copperspice/doxypress/releases/download/dp-1.4.2/doxypress-1.4.2-ubuntu20.04-x64.tar.bz2

**Comment by rleh** [comment]
Thank you very much, I think that's very cool!
This way we don't have to update quickly and old Docker images can be rebuilt in the future.

**Comment by salkinium** [comment]
Note to self: update the Homebrew URL: https://github.com/modm-ext/homebrew-modm/blob/master/doxypress.rb#L7

**Comment by rleh** [comment]
Lets wait until we see that there are no problems in modm-io/modm#815 and then merge this.

Update: Looks fine!

**Comment by rleh** [comment]
> Note to self: update the Homebrew URL: https://github.com/modm-ext/homebrew-modm/blob/master/doxypress.rb#L7

👍🏽, but: copperspice/doxypress#47

**Pull request merged**
