### PR TITLE
Add clang-format

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Comment by salkinium** [comment]
Do you want to enforce code style in modm? I'd be ok with that if it was easy to run clang-format on new code, perhaps [the existing script](https://github.com/modm-io/modm/blob/develop/tools/scripts/clang-format.sh) is enough.

**Review by salkinium — APPROVED** [review]

**Comment by rleh** [comment]
> Do you want to enforce code style in modm? I'd be ok with that if it was easy to run clang-format on new code, perhaps [the existing script](https://github.com/modm-io/modm/blob/develop/tools/scripts/clang-format.sh) is enough.

Primarily I also use the image at @DroidDrive for CI, and there clang-format is very useful because there are no intense code reviews (compared to modm).

**Comment by salkinium** [comment]
Ok great, please report back some time later how it worked out for you and what issues you solved how, so we can apply this to modm perhaps.

**Comment by rleh** [comment]
The `clang-format` provided by Ubuntu 20.04 is version 10. Current version is 14...
Ubuntu also has a package `clang-format-12`, I think I will change this again in the image.

**Comment by chris-durand** [comment]
> The `clang-format` provided by Ubuntu 20.04 is version 10. Current version is 14... Ubuntu also has a package `clang-format-12`, I think I will change this again in the image.

The current release is 13, 14 is the development version. The LLVM project provides up-to-date [Ubuntu packages](https://apt.llvm.org/). I am using those at work as well.

**Comment by rleh** [comment]
I am not a friend of using unnecessarily many external repos.
Is it worth it for version 13 instead of 12; would it possibly help you?

**Comment by chris-durand** [comment]
> I am not a friend of using unnecessarily many external repos. Is it worth it for version 13 instead of 12; would it possibly help you?

Just use 12 if you prefer that. Everyone can install the version they like. 13 has some more C++ language features, but it shouldn't be too relevant here. One example would be `using enum` but that is also not available before gcc 11.

**Pull request merged**
